# Generated by Django 6.0.4 on 2026-05-03 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('activo', models.BooleanField()),
                ('fechaMod', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('activo', models.BooleanField()),
                ('fechaMod', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=300)),
                ('activo', models.BooleanField()),
                ('fechaMod', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='api_alumnos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='api_alumnos.curso')),
            ],
        ),
    ]
